#!/bin/bash

# 快速启动屏生成脚本
# 使用简单的在线工具生成启动屏Logo

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          🚀 启动屏Logo快速生成 🚀                                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📝 需要创建的文件:"
echo ""
echo "  1. launcher_logo.png (512x512, PNG)"
echo "     - 白色背景"
echo "     - 中心有应用Logo"
echo "     - 用于启动屏中心显示"
echo ""
echo "  2. launcher_logo_dark.png (512x512, PNG)"
echo "     - 深色背景"
echo "     - 中心有浅色Logo"
echo "     - 用于深色模式启动屏"
echo ""
echo "  3. android12_logo.png (1024x1024, PNG)"
echo "     - Android 12+自适应图标"
echo "     - 去掉背景"
echo "     - 只保留前景Logo"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎨 推荐工具（按优先级）:"
echo ""
echo "  1️⃣  Canva（最简单）"
echo "     • 访问 https://www.canva.com"
echo "     • 搜索 'Logo' 模板"
echo "     • 选择圆形或方形设计"
echo "     • 添加文字: 'EL' 或 'English Learning'"
echo "     • 使用品牌色: #4CAF50 (绿色)"
echo "     • 导出512x512 PNG"
echo ""
echo "  2️⃣  Figma（专业）"
echo "     • 访问 https://www.figma.com"
echo "     • 创建512x512画布"
echo "     • 添加文字和图形元素"
echo "     • 导出PNG"
echo ""
echo "  3️⃣  Photopea（在线PS）"
echo "     • 访问 https://www.photopea.com"
echo "     • 创建512x512新图像"
echo "     • 设计Logo"
echo "     • 导出PNG"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 设计建议:"
echo ""
echo "  • 简洁为上 - 单一字母或图标"
echo "  • 使用品牌色 - #4CAF50 (绿色)"
echo "  • 保证清晰 - 在小尺寸下也能看清"
echo "  • 避免复杂 - 不要太多细节"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 快速设计方案:"
echo ""
echo "  方案A: 文字Logo"
echo "    • 文字: 'EL' 或 'Eng' 或 '英语学习'"
echo "    • 字体: Arial Black, Helvetica Bold"
echo "    • 颜色: 白色 (#FFFFFF)"
echo "    • 背景: #4CAF50 (绿色)"
echo ""
echo "  方案B: 图标Logo"
echo "    • 图标: 📚 书本 📖 🎓"
echo "    • 放置在中心"
echo "    • 大小: 256x256像素"
echo ""
echo "  方案C: 组合Logo"
echo "    • 上部: 书本图标"
echo "    • 下部: 'English Learning' 文字"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 快速生成步骤（Canva方案）:"
echo ""
echo "  1. 打开 https://www.canva.com"
echo "  2. 注册/登录（免费）"
echo "  3. 点击 '创建设计' → '自定义尺寸'"
echo "  4. 输入 512 x 512 px"
echo "  5. 选择 '文档' → '纯色'"
echo "  6. 选择绿色 (#4CAF50)"
echo "  7. 点击 '元素' → '文字'"
echo "  8. 添加 'EL' 或 'Eng' 文字"
echo "  9. 调整字体大小到最大"
echo "  10. 设置文字颜色为白色"
echo "  11. 导出 → PNG → 下载"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💾 保存位置:"
echo ""
echo "  将文件保存到:"
echo "  assets/icon/launcher_logo.png"
echo "  assets/icon/launcher_logo_dark.png"
echo "  assets/icon/android12_logo.png"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 配置和生成:"
echo ""
echo "  文件准备好后，运行:"
echo "  flutter pub get"
echo "  flutter pub run flutter_native_splash:create"
echo ""
echo "  这将自动生成所有启动屏资源！"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 开始设计您的启动屏Logo吧！"
echo ""
