#!/bin/bash

# 应用图标资源生成脚本
# 使用在线工具或本地工具生成所有尺寸

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          🎨 应用图标快速生成方案 🎨                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 方案1: 使用在线工具（推荐）"
echo ""
echo "  A. Canva（最简单）"
echo "     1. 访问 https://www.canva.com"
echo "     2. 搜索 'App Icon'"
echo "     3. 选择绿色/教育类模板"
echo "     4. 修改为您的品牌元素"
echo "     5. 下载PNG (1024x1024)"
echo ""
echo "  B. AppIconGenerator（自动生成）"
echo "     1. 访问 https://appicon.co"
echo "     2. 上传1024x1024的PNG图标"
echo "     3. 自动生成所有iOS和Android尺寸"
echo "     4. 下载完整包"
echo ""
echo "  C. MakeAppIcon（简单快速）"
echo "     1. 访问 https://makeappicon.com"
echo "     2. 拖拽1024x1024图标文件"
echo "     3. 自动生成并下载"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 方案2: 使用Flutter插件（开发者友好）"
echo ""
echo "  步骤:"
echo "  1. 添加依赖到 pubspec.yaml:"
echo ""
echo "     dev_dependencies:"
echo "       flutter_launcher_icons: ^0.13.1"
echo ""
echo "  2. 配置图标设置:"
echo ""
echo "     flutter_icons:"
echo "       android: true"
echo "       ios: true"
echo "       image_path: 'assets/icon/app_icon.png'"
echo "       adaptive_icon_background: '#4CAF50'"
echo "       adaptive_icon_foreground: 'assets/icon/app_icon_foreground.png'"
echo ""
echo "  3. 运行生成命令:"
echo ""
echo "     flutter pub get"
echo "     flutter pub run flutter_launcher_icons"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 方案3: 使用Figma（专业设计）"
echo ""
echo "  1. 访问 https://www.figma.com"
echo "  2. 使用 'App Icon' 模板"
echo "  3. 自定义设计"
echo "  4. 导出1024x1024 PNG"
echo "  5. 使用AppIconGenerator生成所有尺寸"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 方案4: 快速生成简单图标（用于测试）"
echo ""
echo "  使用ImageMagick命令行工具:"
echo ""
echo "  # 安装ImageMagick"
echo "  brew install imagemagick"
echo ""
echo "  # 生成512x512图标"
echo "  convert -size 512x512 xc:#4CAF50 \\"
echo "          -font Arial-Bold \\"
echo "          -pointsize 200 \\"
echo "          -fill white \\"
echo "          -gravity center \\"
echo "          -annotate +0+0 'EL' \\"
echo "          assets/icon/app_icon_512.png"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 推荐方案（按优先级）:"
echo ""
echo "  1️⃣  使用Canva（最简单，5分钟）"
echo "  2️⃣  使用AppIconGenerator（自动生成，10分钟）"
echo "  3️⃣  使用flutter_launcher_icons（集成到项目，15分钟）"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 后续步骤:"
echo ""
echo "  1. 创建1024x1024的PNG图标"
echo "  2. 使用上述任一方案生成所有尺寸"
echo "  3. 将生成的文件放到对应目录:"
echo "     - Android: android/app/src/main/res/mipmap-*/"
echo "     - iOS: ios/Runner/Assets.xcassets/AppIcon.appiconset/"
echo ""
echo "🎉 开始创建您的应用图标吧！"
echo ""
