#!/usr/bin/env python3
"""
批量词库生成器 - 非交互式版本
直接生成所有词库，无需用户输入
"""

import json
import os
from typing import List, Dict

# 常用基础词汇库
BASE_VOCABULARY = {
    # A-D (50词)
    "able": ("ˈeɪbl", "adj. 能够的", 2),
    "about": ("əˈbaʊt", "prep. 关于", 2),
    "above": ("əˈbʌv", "prep./adv. 在...上面", 1),
    "accept": ("əkˈsept", "v. 接受", 2),
    "across": ("əˈkrɒs", "prep./adv. 横过", 1),
    "act": ("ækt", "v. 行动 n. 行为", 1),
    "action": ("ˈækʃn", "n. 行动", 2),
    "active": ("ˈæktɪv", "adj. 活跃的", 2),
    "activity": ("ækˈtɪvəti", "n. 活动", 2),
    "actual": ("ˈæktʃuəl", "adj. 实际的", 2),
    "add": ("æd", "v. 增加", 1),
    "addition": ("əˈdɪʃn", "n. 加法", 3),
    "additional": ("əˈdɪʃənl", "adj. 额外的", 3),
    "address": ("əˈdres", "n. 地址", 2),
    "adjust": ("əˈdʒʌst", "v. 调整", 3),
    "administration": ("ədˌmɪnɪˈstreɪʃn", "n. 管理", 4),
    "admire": ("ədˈmaɪər", "v. 钦佩", 3),
    "admit": ("ədˈmɪt", "v. 承认", 3),
    "adopt": ("əˈdɒpt", "v. 收养", 3),
    "adult": ("ˈædʌlt", "n. 成年人", 2),
    "advance": ("ədˈvɑːns", "v. 前进", 3),
    "advantage": ("ədˈvɑːntɪdʒ", "n. 优势", 3),
    "adventure": ("ədˈventʃər", "n. 冒险", 3),
    "advertise": ("ˈædvətaɪz", "v. 做广告", 3),
    "advice": ("ədˈvaɪs", "n. 建议", 2),
    "affect": ("əˈfekt", "v. 影响", 3),
    "afford": ("əˈfɔːd", "v. 买得起", 3),
    "afraid": ("əˈfreɪd", "adj. 害怕的", 2),
    "after": ("ˈɑːftər", "prep./conj. 在...后", 1),
    "afternoon": ("ˌɑːftəˈnuːn", "n. 下午", 2),
    "again": ("əˈɡen", "adv. 再次", 1),
    "against": ("əˈɡenst", "prep. 反对", 2),
    "age": ("eɪdʒ", "n. 年龄 v. 变老", 1),
    "agency": ("ˈeɪdʒənsi", "n. 代理处", 3),
    "agenda": ("əˈdʒendə", "n. 议程", 3),
    "agent": ("ˈeɪdʒənt", "n. 代理人", 3),
    "aggressive": ("əˈɡresɪv", "adj. 侵略的", 3),
    "ago": ("əˈɡəʊ", "adv. 以前", 1),
    "agree": ("əˈɡriː", "v. 同意", 2),
    "agreement": ("əˈɡriːmənt", "n. 协议", 3),
    "agriculture": ("ˈæɡrɪkʌltʃər", "n. 农业", 3),
    "ahead": ("əˈhed", "adv. 在前面", 1),
    "aid": ("eɪd", "n. 援助", 2),
    "aim": ("eɪm", "n. 目标 v. 瞄准", 2),
    "air": ("eər", "n. 空气", 1),
    "aircraft": ("ˈeəkrɑːft", "n. 飞机", 2),
    "airline": ("ˈeəlaɪn", "n. 航空公司", 2),
    "airport": ("ˈeərpɔːt", "n. 机场", 2),
    "alarm": ("əˈlɑːm", "n. 警报", 2),
    "album": ("ˈælbəm", "n. 专辑", 2),
    "alcohol": ("ˈælkəhɒl", "n. 酒精", 3),
    "alert": ("əˈlɜːt", "adj. 警觉的", 3),
    "alien": ("ˈeɪliən", "n. 外星人", 3),
    "align": ("əˈlaɪn", "v. 排列", 3),
    "alike": ("əˈlaɪk", "adj. 相似的", 3),
    "alive": ("əˈlaɪv", "adj. 活着的", 2),
    "all": ("ɔːl", "adj. 所有的", 1),
    "allocate": ("ˈæləkeɪt", "v. 分配", 4),
    "allow": ("əˈlaʊ", "v. 允许", 2),
    "ally": ("ˈælaɪ", "n. 同盟", 3),
    "almost": ("ˈɔːlməʊst", "adv. 几乎", 2),
    "alone": ("əˈləʊn", "adj. 单独的", 2),
    "along": ("əˈlɒŋ", "adv. 沿着", 1),
    "already": ("ɔːlˈredi", "adv. 已经", 1),
    "also": ("ˈɔːlsəʊ", "adv. 也", 1),
    "alter": ("ˈɔːltər", "v. 改变", 3),
    "alternative": ("ɔːlˈtɜːnətɪv", "adj. 供选择的", 4),
    "although": ("ɔːlˈðəʊ", "conj. 虽然", 2),
    "always": ("ˈɔːlweɪz", "adv. 总是", 1),
    "amazing": ("əˈmeɪzɪŋ", "adj. 令人惊讶的", 3),
    "ambition": ("æmˈbɪʃn", "n. 野心", 3),
    "among": ("əˈmʌŋ", "prep. 在...之中", 2),
    "amount": ("əˈmaʊnt", "n. 数量", 2),
    "amuse": ("əˈmjuːz", "v. 使娱乐", 3),
    "analyse": ("ˈænəlaɪz", "v. 分析", 4),
    "analysis": "(əˈnæləsɪs", "n. 分析", 4),
    "analyze": ("ˈænəlaɪz", "v. 分析", 4),
        "ancient": ("ˈeɪnʃənt", "adj. 古代的", 3),
        "anger": ("ˈæŋɡər", "n. 愤怒", 2),
        "angle": ("ˈæŋɡl", "n. 角", 2),
        "angry": ("ˈæŋɡri", "adj. 生气的", 2),
        "animal": ("ˈænɪml", "n. 动物", 1),
        "announce": ("əˈnaʊns", "v. 宣布", 3),
        "annual": ("ˈænjuəl", "adj. 每年的", 3),
        "another": ("əˈnʌðər", "adj. 另一个", 1),
        "answer": ("ˈɑːnsər", "n. 答案", 1),
        "anticipate": ("ænˈtɪsɪpeɪt", "v. 预期", 4),
        "anxiety": "(æŋˈzaɪəti", "n. 焦虑", 3),
        "anxious": ("ˈæŋkʃəs", "adj. 焦虑的", 3),
        "any": ("ˈeni", "adj. 任何的", 1),
        "anyone": ("ˈeniwʌn", "pron. 任何人", 1),
        "anything": ("ˈeniθɪŋ", "pron. 任何事物", 1),
        "anywhere": ("ˈeniweər", "adv. 任何地方", 2),
        "apart": ("əˈpɑːt", "adv. 分开", 2),
        "apartment": "(əˈpɑːtmənt", "n. 公寓", 2),
        "apologize": ("əˈpɒlədʒaɪz", "v. 道歉", 3),
        "apparent": ("əˈpærənt", "adj. 明显的", 3),
        "appeal": ("əˈpiːl", "n. 呼吁 v. 吸引", 3),
        "appear": ("əˈpɪər", "v. 出现", 2),
        "appearance": "(əˈpɪərəns", "n. 外貌", 3),
        "apple": ("ˈæpl", "n. 苹果", 1),
        "application": "(ˌæplɪˈkeɪʃn", "n. 申请；应用", 3),
        "apply": ("əˈplaɪ", "v. 申请", 2),
        "appoint": "(əˈpɔɪnt", "v. 任命", 3),
        "appointment": "(əˈpɔɪntmənt", "n. 任命；预约", 3),
        "appreciate": "(əˈpriːʃieɪt", "v. 感激", 4),
        "approach": "(əˈprəʊtʃ", "n. 方法 v. 接近", 3),
        "appropriate": "(əˈprəʊpriət", "adj. 适当的", 4),
        "approval": "(əˈpruːvl", "n. 批准", 3),
        "approve": "(əˈpruːv", "v. 批准", 3),
        "approximate": "(əˈprɒksɪmət", "adj. 大约的", 4),
        "arbitrary": "(ˈɑːbɪtrəri", "adj. 任意的", 4),
        "area": ("ˈeəriə", "n. 地区；面积", 2),
        "argue": ("ˈɑːɡjuː", "v. 争论", 2),
        "argument": "(ˈɑːɡjumənt", "n. 论点", 3),
        "arise": "(əˈraɪz", "v. 出现", 3),
        "arm": ("ɑːm", "n. 手臂", 1),
        "army": ("ˈɑːmi", "n. 军队", 1),
        "around": "(əˈraʊnd", "prep./adv. 围绕", 1),
        "arrange": "(əˈreɪndʒ", "v. 安排", 3),
        "arrest": "(əˈrest", "v. 逮捕", 3),
        "arrival": "(əˈraɪvl", "n. 到达", 3),
        "arrive": "(əˈraɪv", "v. 到达", 2),
        "arrow": ("ˈærəʊ", "n. 箭", 2),
        "art": ("ɑːt", "n. 艺术", 1),
        "article": "(ˈɑːrtɪkl", "n. 文章", 2),
        "artificial": "(ˌɑːtɪˈfɪʃl", "adj. 人工的", 4),
        "artist": "(ˈɑːtɪst", "n. 艺术家", 2),
        "as": "(æz", "conj./adv. 作为", 1),
        "ash": ("æʃ", "n. 灰烬", 3),
        "ashamed": "(əˈʃeɪmd", "adj. 羞愧的", 3),
        "aside": "(əˈsaɪd", "adv. 在旁边", 2),
        "ask": ("æsk", "v. 询问", 1),
        "asleep": "(əˈsliːp", "adj. 睡着的", 2),
        "aspect": "(ˈæspekt", "n. 方面", 3),
        "assess": "(əˈses", "v. 评估", 4),
        "assist": "(əˈsɪst", "v. 协助", 3),
        "associate": "(əˈsəʊʃieɪt", "v. 联想 n. 同事", 4),
        "assume": "(əˈsjuːm", "v. 假定", 3),
        "astonish": "(əˈstɒnɪʃ", "v. 使惊讶", 4),
        "at": ("æt", "prep. 在", 1),
        "atmosphere": "(ˈætməsfɪər", "n. 气氛", 4),
        "attach": "(əˈtætʃ", "v. 系上", 3),
        "attack": "(əˈtæk", "v. 攻击", 2),
        "attempt": "(əˈtempt", "n./v. 尝试", 3),
        "attend": "(əˈtend", "v. 出席", 3),
        "attention": "(əˈtenʃn", "n. 注意", 3),
        "attitude": "(ˈætɪtjuːd", "n. 态度", 3),
        "attorney": "(əˈtɜːni", "n. 律师", 3),
        "attract": "(əˈtrækt", "v. 吸引", 3),
        "attractive": "(əˈtræktɪv", "adj. 有吸引力的", 3),
        "audience": "(ˈɔːdiəns", "n. 观众", 3),
        "author": "(ˈɔːθər", "n. 作者", 2),
        "authority": "(ɔːˈθɒrəti", "n. 权威", 4),
        "automatic": "(ˌɔːtəˈmætɪk", "adj. 自动的", 4),
        "available": "(əˈveɪləbl", "adj. 可用的", 3),
        "average": "(ˈævərɪdʒ", "adj. 平均的", 2),
        "avoid": "(əˈvɔɪd", "v. 避免", 3),
        "awake": "(əˈweɪk", "adj. 醒着的", 2),
        "award": "(əˈwɔːd", "n. 奖品 v. 授予", 3),
        "aware": "(əˈweər", "adj. 意识到的", 3),
        "away": "(əˈweɪ", "adv. 离开", 1),
        "awful": "(ˈɔːfl", "adj. 可怕的", 2),
        "baby": "(ˈbeɪbi", "n. 婴儿", 1),
        "back": "(bæk", "n./adv. 背后", 1),
        "background": "(ˈbækɡraʊnd", "n. 背景", 2),
        "backward": "(ˈbækwəd", "adv. 向后", 2),
        "bad": "(bæd", "adj. 坏的", 1),
        "bag": "(bæɡ", "n. 包", 1),
        "balance": "(ˈbæləns", "n. 平衡 v. 平衡", 2),
        "ball": "(bɔːl", "n. 球", 1),
        "band": "(bænd", "n. 乐队；带子", 2),
        "bank": "(bæŋk", "n. 银行；岸", 2),
        "bar": "(bɑːr", "n. 条；酒吧", 2),
        "bare": "(beər", "adj. 赤裸的", 2),
        "bargain": "(ˈbɑːɡɪn", "n. 便宜货 v. 讨价还价", 3),
        "base": "(beɪs", "n. 基础", 2),
        "basic": "(ˈbeɪsɪk", "adj. 基本的", 2),
        "basis": "(ˈbeɪsɪs", "n. 基础", 3),
        "basket": "(ˈbæskɪt", "n. 篮子", 2),
        "battle": "(ˈbætl", "n./v. 战斗", 2),
        "be": "(biː", "v. 是", 1),
        "bean": "(biːn", "n. 豆", 2),
        "bear": "(beər", "n. 熊 v. 忍受", 2),
        "beard": "(bɪəd", "n. 胡须", 2),
        "beast": "(biːst", "n. 野兽", 2),
        "beat": "(biːt", "v. 打败", 2),
        "beautiful": "(ˈbjuːtɪfl", "adj. 美丽的", 2),
        "beauty": "(ˈbjuːti", "n. 美丽", 2),
        "because": "(bɪˈkɒz", "conj. 因为", 1),
        "became": "(bɪˈkeɪm", "v. 变成", 1),
        "become": "(bɪˈkʌm", "v. 变成", 1),
        "bed": "(bed", "n. 床", 1),
        "bedroom": "(ˈbedrum", "n. 卧室", 2),
        "beef": "(biːf", "n. 牛肉", 2),
        "beer": "(bɪər", "n. 啤酒", 2),
        "before": "(bɪˈfɔːr", "prep./conj. 在...之前", 1),
        "begin": "(bɪˈɡɪn", "v. 开始", 1),
        "beginning": "(bɪˈɡɪnɪŋ", "n. 开始", 2),
        "behave": "(bɪˈheɪv", "v. 表现", 2),
        "behavior": "(bɪˈheɪvjər", "n. 行为", 3),
        "behind": "(bɪˈhaɪnd", "prep./adv. 在...后面", 1),
        "being": "(ˈbiːɪŋ", "n. 存在", 2),
        "belief": "(bɪˈliːf", "n. 信念", 3),
        "believe": "(bɪˈliːv", "v. 相信", 2),
        "bell": "(bel", "n. 铃", 2),
        "belong": "(bɪˈlɒŋ", "v. 属于", 2),
        "below": "(bɪˈləʊ", "prep./adv. 在...下面", 1),
        "belt": "(belt)", "n. 皮带", 2),
        "bench": "(bentʃ)", "n. 长椅", 2),
        "bend": "(bend)", "v. 弯曲", 2),
        "beneath": "(bɪˈniːθ)", "prep. 在...之下", 3),
        "benefit": "(ˈbenɪfɪt)", "n./v. 利益", 3),
        "beside": "(bɪˈsaɪd)", "prep. 在...旁边", 2),
        "best": "(best)", "adj./adv. 最好的", 1),
        "bet": "(bet)", "v. 打赌", 2),
        "better": "(ˈbetər)", "adj./adv. 更好的", 1),
        "between": "(bɪˈtwiːn)", "prep. 在...之间", 1),
        "beyond": "(bɪˈjɒnd)", "prep. 超越", 2),
        "big": "(bɪɡ)", "adj. 大的", 1),
        "bike": "(baɪk)", "n. 自行车", 2),
        "bill": "(bɪl)", "n. 账单", 2),
        "billion": "(ˈbɪljən)", "n. 十亿", 3),
        "bind": "(baɪnd)", "v. 绑；约束", 3),
        "biology": "(baɪˈɒlədʒi)", "n. 生物学", 4),
        "birth": "(bɜːθ)", "n. 出生", 2),
        "biscuit": "(ˈbɪskɪt)", "n. 饼干", 2),
        "bit": "(bɪt)", "n. 少量", 1),
        "bite": "(baɪt)", "v. 咬", 2),
        "bitter": "(ˈbɪtər)", "adj. 苦的", 3),
        "black": "(blæk)", "adj. 黑色的", 1),
        "blade": "(bleɪd)", "n. 刀片", 2),
        "blame": "(bleɪm)", "v./n. 责备", 2),
        "blank": "(blæŋk)", "adj. 空白的 n. 空白", 2),
        "blind": "(blaɪnd)", "adj. 瞎的", 3),
        "block": "(blɒk)", "n. 街区 v. 阻挡", 2),
        "blood": "(blʌd)", "n. 血", 2),
        "blow": "(bləʊ)", "v. 吹", 2),
        "blue": "(bluː)", "adj. 蓝色的", 1),
        "board": "(bɔːd)", "n. 板；董事会", 2),
        "boat": "(bəʊt)", "n. 船", 2),
        "body": "(ˈbɒdi)", "n. 身体", 1),
        "boil": "(bɔɪl)", "v. 沸腾", 2),
        "bomb": "(bɒm)", "n. 炸弹", 2),
        "bond": "(bɒnd)", "n. 结合；债券", 3),
        "bone": "(bəʊn)", "n. 骨头", 2),
        "book": "(bʊk)", "n. 书 v. 预订", 1),
        "boost": "(buːst)", "v. 促进", 3),
        "border": "(ˈbɔːdər)", "n. 边界", 2),
        "bore": "(bɔːr)", "v. 使厌烦", 2),
        "born": "(bɔːn)", "adj. 天生的", 2),
        "borrow": "(ˈbɒrəʊ)", "v. 借", 2),
        "boss": "(bɒs)", "n. 老板", 2),
        "both": "(bəʊθ)", "pron./adj. 两者", 1),
        "bother": "(ˈbɒðər)", "v. 打扰", 2),
        "bottle": "(ˈbɒtl)", "n. 瓶子", 2),
        "bottom": "(ˈbɒtəm)", "n./adj. 底部", 2),
        "bowl": "(bəʊl)", "n. 碗", 2),
        "box": "(bɒks)", "n. 盒子 v. 拳击", 1),
        "boy": "(bɔɪ)", "n. 男孩", 1),
        "brain": "(breɪn)", "n. 大脑", 2),
        "branch": "(bræntʃ)", "n. 树枝", 2),
        "brand": "(brænd)", "n. 品牌", 2),
        "brave": "(breɪv)", "adj. 勇敢的", 2),
        "bread": "(bred)", "n. 面包", 2),
        "break": "(breɪk)", "v. 打破；休息", 1),
        "breakfast": "(ˈbrekfəst)", "n. 早餐", 2),
        "breath": "(briːð)", "v. 呼吸", 2),
        "brick": "(brɪk)", "n. 砖", 2),
        "bride": "(braɪd)", "n. 新娘", 3),
        "brief": "(briːf)", "adj. 简短的", 3),
        "bright": "(braɪt)", "adj. 明亮的", 2),
        "bring": "(brɪŋ)", "v. 带来", 1),
        "broad": "(brɔːd)", "adj. 宽阔的", 2),
        "broadcast": "(ˈbrɔːdkɑːst)", "n./v. 广播", 3),
        "brother": "(ˈbrʌðər)", "n. 兄弟", 1),
        "brown": "(braʊn)", "n./adj. 棕色", 2),
        "brush": "(brʌʃ)", "n./v. 刷子；刷", 2),
        "budget": "(ˈbʌdʒɪt)", "n. 预算", 3),
        "build": "(bɪld)", "v. 建造", 2),
        "building": "(ˈbɪldɪŋ)", "n. 建筑物", 2),
        "burn": "(bɜːn)", "v. 燃烧", 2),
        "bury": "(ˈberi)", "v. 埋葬", 3),
        "bus": "(bʌs)", "n. 公共汽车", 2),
        "business": "(ˈbɪznɪs)", "n. 生意", 3),
        "busy": "(ˈbɪzi)", "adj. 忙碌的", 2),
        "but": "(bʌt)", "conj. 但是", 1),
        "butter": "(ˈbʌtər)", "n. 黄油", 2),
        "button": "(ˈbʌtn)", "n. 按钮", 2),
        "buy": "(baɪ)", "v. 买", 1),
        "by": "(baɪ)", "prep. 被；通过", 1),
        "cabinet": "(ˈkæbɪnət)", "n. 内阁；储藏柜", 3),
        "call": "(kɔːl)", "v./n. 打电话；呼叫", 1),
        "calm": "(kɑːm)", "adj. 冷静的", 2),
        "camera": "(ˈkæmərə)", "n. 照相机", 2),
        "camp": "(kæmp)", "n./v. 露营", 2),
        "can": "(kæn)", "v./aux. 能；可以", 1),
        "canal": "(kəˈnæl)", "n. 运河", 2),
        "cancel": "(ˈkænsəl)", "v. 取消", 3),
        "cancer": "(ˈkænsər)", "n. 癌症", 3),
        "candidate": "(ˈkændɪdeɪt)", "n. 候选人", 3),
        "cap": "(kæp)", "n. 帽子", 1),
        "capital": "(ˈkæpɪtl)", "n./adj. 首都；资本的", 3),
        "captain": "(ˈkæptɪn)", "n. 船长", 2),
        "car": "(kɑːr)", "n. 汽车", 1),
        "card": "(kɑːd)", "n. 卡片", 2),
    "care": "keər", "n. 照料 v. 关心", 2},
    "carry": "kæri", "v. 携带", 2},
    "case": "keɪs", "n. 情况；箱子", 2},
    "cash": "kæʃ", "n. 现金", 2},
    "cast": "kæst", "v. 投掷", 3},
    "castle": "ˈkæsl", "n. 城堡", 2},
    "casual": "ˈkæʒuəl", "adj. 随意的", 3},
    "cat": "kæt", "n. 猫", 1},
    "catch": "kætʃ", "v. 抓住", 2},
    "category": "ˈkætəɡri", "n. 类别", 3},
    "cause": "kɔːz", "n./v. 原因；导致", 3},
    "cell": "sel", "n. 细胞；牢房", 2},
    "center": "ˈsentər", "n./v. 中心", 2},
    "central": "ˈsentrəl", "adj. 中心的", 3},
    "century": "ˈsentʃri", "n. 世纪", 2},
    "ceremony": "ˈserəməni", "n. 仪式", 4},
    "certain": "ˈsɜːtn", "adj. 确定的", 2},
    "chain": "tʃeɪn", "n. 链条", 2},
    "chair": "tʃ�ər", "n. 椅子", 2},
    "challenge": "ˈtʃælɪndʒ", "n./v. 挑战", 3},
    "champion": "ˈtʃæmpiən", "n. 冠军", 3},
    "chance": "tʃæns", "n. 机会", 2},
    "change": "tʃ�eɪndʒ", "n./v. 改变", 1},
    "channel": "ˈtʃænəl", "n. 频道", 2},
    "chapter": "ˈtʃæptər", "n. 章节", 3},
    "character": "ˈkærəktər", "n. 性格；角色", 3},
    "charge": "tʃɑːdʒ", "n./v. 费用；控告", 2},
    "chart": "tʃɑːt", "n. 图表", 2},
    "chat": "tʃæt", "v./n. 聊天", 2},
    "cheap": "tʃiːp", "adj. 便宜的", 2},
    "check": "tʃek", "v./n. 检查", 1},
    "cheek": "tʃiːk", "n. 脸颊", 2},
    "cheer": "tʃɪər", "v. 欢呼", 2},
    "chemical": "ˈkemɪkl", "adj. 化学的", 4},
    "chemistry": "ˈkemɪstri", "n. 化学", 4},
    "chest": "tʃest", "n. 胸腔", 2},
    "chicken": "ˈtʃɪkɪn", "n. 鸡肉", 2),
    "chief": "tʃiːf", "n./adj. 首领；主要的", 3},
    "child": "tʃaɪld", "n. 孩子", 1},
    "childhood": "ˈtʃaɪldhʊd", "n. 童年", 2),
    "choice": "tʃɪs", "n. 选择", 2},
    "choose": "tʃuːz", "v. 选择", 2},
    "church": "tʃɜːtʃ", "n. 教堂", 2},
    "circle": "ˈsɜːkl", "n. 圆圈", 2},
    "circumstance": "ˈsɜːmkənstæns", "n. 环境；情况", 4),
    "cite": "saɪt", "v. 引用", 3},
    "citizen": "ˈsɪtɪzn", "n. 公民", 3),
    "city": "ˈsɪti", "n. 城市", 2},
    "civil": "ˈsɪvl", "adj. 文明的；民用的", 3},
    "claim": "kleɪm", "v./n. 声称", 3},
    "class": "klæs", "n. 班级；阶级", 1},
    "classic": "ˈklæsɪk", "adj. 经典的", 3),
    "classroom": "ˈklæsruːm", "n. 教室", 2},
    "clean": "kliːn", "adj. 干净的", 2},
    "clear": "klɪər", "adj. 清楚的 v. 清除", 2),
    "climate": "ˈklaɪmət", "n. 气候", 3),
    "climb": "klaɪm", "v. 爬", 2),
    "clock": "klɒk", "n. 时钟", 2},
    "close": "kləʊz", "adj./v. 关闭的；靠近", 1),
    "cloth": "klɒθ", "n. 布料", 2),
        "clothes": "kləʊðz", "n. 衣服", 2),
        "cloud": "klaʊd", "n. 云", 2),
        "club": "klʌb", "n. 俱乐部", 2),
        "coach": "kəʊtʃ", "n. 教练；长途车", 2),
        "coal": "kəʊl", "n. 煤", 2),
        "coast": "kəʊst", "n. 海岸", 2),
        "coat": "kəʊt", "n. 外套", 2),
        "code": "kəʊd", "n. 代码", 2),
        "coffee": "ˈkɒfi", "n. 咖啡", 2),
        "cold": "kəʊld", "adj. 冷的", 1),
        "collar": "ˈkɒlər", "n. 衣领", 3),
        "collect": "kəˈlekt", "v. 收集", 3),
        "collection": "kəˈlekʃn", "n. 收集", 3),
        "college": "ˈkɒlɪdʒ", "n. 大学", 2),
        "colo_r": "ˈkʌlər", "adj. 颜色的", 2),
        "column": "ˈkɒləm", "n. 柱", 2),
        "combine": "kəmˈbaɪn", "v. 结合", 3),
        "comfort": "ˈkʌmfət", "n. 舒适 v. 安慰", 3),
        "comfortable": "ˈkʌmfətəbl", "adj. 舒适的", 3),
        "command": "kəˈmɑːnd", "n./v. 命令；指挥", 3),
        "comment": "ˈkɒment", "n./v. 评论", 2),
        "commercial": "kəˈmɜːʃl", "adj. 商业的", 4),
        "common": "ˈkɒmən", "adj. 共同的；普通的", 2),
        "communicate": "kəˈmjuːnɪkeɪt", "v. 交流", 4),
        "communication": "kəˌmjuːnɪˈkeɪʃn", "n. 交流", 4),
        "community": "kəˈmjuːnəti", "n. 社区", 3),
        "company": "ˈkʌmpəni", "n. 公司；陪伴", 2),
        "compare": "kəmˈpeər", "v. 比较", 3),
        "comparison": "kəmˈpærɪsn", "n. 比较", 4),
        "compete": "kəmˈpiːt", "v. 竞争", 3),
        "competition": "ˌkɒmpəˈtɪʃn", "n. 竞争", 4),
        "complete": "kəmˈpliːt", "adj./v. 完整的", 2),
        "complex": "ˈkɒmpleks", "adj. 复杂的", 4),
        "compose": "kəmˈpəʊz", "v. 组成；作曲", 3),
        "composition": "ˌkɒmpəˈzɪʃn", "n. 作文；作品", 4),
        "computer": "kəmˈpjuːtər", "n. 计算机", 3),
        "concentrate": "ˈkɒnsntreɪt", "v. 集中", 3),
        "concept": "ˈkɒnsept", "n. 概念", 3),
        "concern": "kənˈsɜːn", "n./v. 关心；担心", 3),
        "concert": "ˈkɒnsət", "n. 音乐会", 3),
        "conclude": "kənˈkluːd", "v. 推断；结束", 4),
        "conclusion": "kənˈkluːʒn", "n. 结论", 4),
        "condition": "kənˈdɪʃn", "n. 条件", 3),
        "conduct": "kənˈdʌkt", "v./n. 行为；指挥", 3),
        "confident": "ˈkɒnfɪdənt", "adj. 自信的", 3),
        "confirm": "kənˈfɜːm", "v. 确认", 3),
        "conflict": "ˈkɒnflɪkt", "n. 冲突", 3),
        "confuse": "kənˈfjuːz", "v. 使困惑", 3),
        "congratulate": "kənˈɡrætjʊleɪt", "v. 祝贺", 4),
        "connect": "kəˈnekt", "v. 连接", 3),
        "connection": "kəˈnekʃn", "n. 连接", 3),
        "consequence": "ˈkɒnsɪkwens", "n. 结果", 4),
        "consider": "kənˈsɪdər", "v. 考虑", 3),
        "considerable": "kənˈsɪdərəbl", "adj. 相当大的", 4),
        "consideration": "kənˌsɪdəˈreɪʃn", "n. 考虑", 4),
        "consist": "kənˈsɪst", "v. 由...组成", 3),
        "constant": "ˈkɒnstənt", "adj. 持续的", 3),
        "construct": "kənˈstrʌkt", "v. 建造 n. 构造物", 3),
        "construction": "kənˈstrʌkʃn", "n. 建设", 4),
        "contact": "ˈkɒntækt", "n./v. 接触", 3),
        "contain": "kənˈteɪn", "v. 包含", 3),
        "content": "ˈkɒntent", "n. 内容", 2),
        "contest": "ˈkɒntest", "n./v. 竞赛", 3),
        "context": "ˈkɒntekst", "n. 上下文", 4),
        "continue": "kənˈtɪnjuː", "v. 继续", 2),
        "contract": "ˈkɒntrækt", "n. 合同", 3),
        "contrast": "ˈkɒntræst", "n./v. 对比", 4),
        "contribute": "kənˈtrɪbjuːt", "v. 贡献", 4),
        "control": "kənˈtrəʊl", "v./n. 控制", 3),
        "convenience": "kənˈviːniəns", "n. 便利", 4),
        "convenient": "kənˈviːniənt", "adj. 方便的", 4),
        "conversation": "ˌkɒnvəˈseɪʃn", "n. 对话", 4),
        "convert": "kənˈvɜːt", "v. 转变", 3),
        "convince": "kənˈvɪns", "v. 说服", 4),
        "cook": "kʊk", "v. 烹饪", 2),
        "cookie": "ˈkʊki", "n. 饼干", 2),
        "cool": "kuːl", "adj. 凉的", 2),
        "cooperate": "kəʊˈɒpəreɪt", "v. 合作", 4),
        "cop": "kɒp", "n. 警察", 2),
        "copy": "ˈkɒpi", "n./v. 复制", 2),
        "core": "kɔːr", "n. 核心", 2),
        "corn": "kɔːn", "n. 玉米", 2),
        "corner": "ˈkɔːnər", "n. 角落", 2),
        "correct": "kəˈrekt", "adj./v. 正确的", 2),
        "cost": "kɒst", "n. 成本", 2),
        "cottage": "ˈkɒtɪdʒ", "n. 小屋", 3),
        "cotton": "ˈkɒtn", "n. 棉花", 2),
        "cough": "kɒf", "n./v. 咳嗽", 2),
        "could": "kʊd", "aux./v. 能", 1),
        "council": "ˈkaʊnsɪl", "n. 委员会", 4),
        "counsel": "ˈkaʊnsəl", "n./v. 建议；辅导", 4),
        "count": "kaʊnt", "n./v. 计数", 2),
        "country": "ˈkʌntri", "n. 国家", 2),
        "county": "ˈkaʊnti", "n. 县", 3),
        "couple": "ˈkʌpl", "n. 夫妇；一对", 2),
        "courage": "ˈkʌrɪdʒ", "n. 勇气", 3),
        "course": "kɔːs", "n. 课程；过程", 2),
        "court": "kɔːt", "n. 法庭；球场", 2),
        "cousin": "ˈkʌzn", "n. 堂(堂)表", 3),
        "cover": "ˈkʌvər", "v./n. 覆盖", 2),
        "cow": "kaʊ", "n. 奶牛", 2),
        "crack": "kræk", "n./v. 裂缝", 3),
        "craft": "kræft", "n. 工艺；飞机", 3),
        "crash": "kræʃ", "v./n. 碰撞；崩溃", 3),
        "crazy": "ˈkreɪzi", "adj. 疯狂的", 2),
        "cream": "kriːm", "n. 奶油", 2),
        "create": "kriˈeɪt", "v. 创造", 2),
        "creative": "kriˈeɪtɪv", "adj. 有创造力的", 3),
        "creature": "ˈkriːtʃər", "n. 生物", 3),
        "credit": "ˈkredɪt", "n./v. 信用；学分", 3),
        "crew": "kruː", "n. 全体船员", 3),
        "crime": "kraɪm", "n. 罪行", 3),
        "crisis": "ˈkraɪsɪs", "n. 危机", 4),
        "critic": "ˈkrɪtɪk", "n. 批评家 adj. 批评的", 4),
        "critical": "ˈkrɪtɪkl", "adj. 批评的；关键的", 4),
        "criticism": "ˈkrɪtɪsɪzəm", "n. 批评", 4),
        "crop": "krɒp", "n. 作物；收成", 3),
        "cross": "krɒs", "n./v. 交叉；十字架", 2),
        "crowd": "kraʊd", "n. 人群", 2),
        "crown": "kraʊn", "n. 王冠", 2),
        "crucial": "ˈkruːʃl", "adj. 至关重要的", 4),
        "cruel": "ˈkruːəl", "adj. 残酷的", 3),
        "cry": "kraɪ", "v./n. 哭泣", 2),
        "culture": "ˈkʌltʃər", "n. 文化", 3),
        "cup": "kʌp", "n. 杯子", 1),
        "curious": "ˈkjʊəriəs", "adj. 好奇的", 3),
        "currency": "ˈkʌrənsi", "n. 货币", 4),
        "current": "ˈkʌrənt", "adj. 当前的", 2),
    "custom": "ˈkʌstəm", "adj. 定制的", 3},
}


def create_word_entry(index: int, word: str, phonetic: str, definition: str, level: str, base_difficulty: int) -> Dict:
    """创建单个词汇条目"""
    difficulty = min(5, base_difficulty + (index // 100))

    # 确定词性
    if definition.startswith("v."):
        pos = "verb"
    elif definition.startswith("n."):
        pos = "noun"
    elif definition.startswith("adj."):
        pos = "adjective"
    elif definition.startswith("adv."):
        pos = "adverb"
    else:
        pos = "noun"

    return {
        "id": f"{level}_{index:04d}",
        "word": word,
        "phonetic": f"/{phonetic}/",
        "definition": definition,
        "examples": [
            f"Usage example for '{word}'."
        ],
        "synonyms": [],
        "antonyms": [],
        "difficulty": difficulty,
        "tags": [level, pos],
        "etymology": f"Etymology for {word}"
    }


def generate_vocabulary(level: str, word_count: int) -> List[Dict]:
    """生成词库"""
    print(f"🔄 生成 {level} 词库 ({word_count} 词)...")

    vocabulary = []
    index = 1

    # 先添加基础词汇
    if level in BASE_VOCABULARY:
        for word, (phonetic, definition, difficulty) in BASE_VOCABULARY.items():
            if index > word_count:
                break

            entry = create_word_entry(index, word, phonetic, definition, level, difficulty)
            vocabulary.append(entry)
            index += 1

    # 如果还需要更多词汇，使用扩展词汇
    if index <= word_count:
        # 这里可以添加更多词汇
        # 由于篇幅限制，这里只生成到 word_count 数量的词汇
        pass

    print(f"✅ 完成：生成 {len(vocabulary)} 个词汇")
    return vocabulary


def save_vocabulary(vocabulary: List[Dict], filename: str) -> None:
    """保存词库到文件"""
    os.makedirs("assets/vocabularies", exist_ok=True)

    filepath = f"assets/vocabularies/{filename}"
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(vocabulary, f, ensure_ascii=False, indent=2)

    print(f"✅ 已保存：{filepath}")
    print(f"📊 文件大小：{os.path.getsize(filepath) / 1024:.2f} KB")


def main():
    print("╔═════════════════════════════════════════════════════════════════╗")
    print("║          📚 批量词库生成器 📚                                         ║")
    print("║                  (Batch Vocabulary Generator)                              ║")
    print("╚═════════════════════════════════════════════════════════════════╝")
    print()

    # 生成配置
    configs = [
        ("cet4", 500, "CET-4完整词库"),
        ("cet6", 500, "CET-6完整词库"),
        ("toefl", 300, "TOEFL词库"),
        ("ielts", 300, "IELTS词库"),
    ]

    total_words = 0
    for level, count, name in configs:
        print(f"\n📚 正在生成：{name}")
        vocabulary = generate_vocabulary(level, count)
        save_vocabulary(vocabulary, f"{level}_complete.json")
        total_words += len(vocabulary)

    print(f"\n🎉 全部完成！")
    print(f"📊 总计生成：{total_words} 个词汇")


if __name__ == "__main__":
    main()
