#!/usr/bin/env python3
"""
综合词库生成器 - 包含数千个真实英语词汇
生成CET4/6、TOEFL、IELTS、GRE等多个级别的完整词库
"""

import json
import os
from typing import List, Dict

# 综合词汇数据库 - 按字母和难度分类
COMPREHENSIVE_VOCABULARY = {
    # A字母词汇
    "abandon": ("əˈbændən", "v. 遗弃；放弃", 3, "cet4"),
    "abbreviation": ("əˌbriːviˈeɪʃn", "n. 缩写", 4, "cet6"),
    "abdicate": ("ˈæbdɪkeɪt", "v. 退位；放弃", 5, "gre"),
    "abide": ("əˈbaɪd", "v. 遵守；忍受", 4, "cet6"),
    "abolish": ("əˈbɒlɪʃ", "v. 废除", 4, "cet6"),
    "absence": ("ˈæbsəns", "n. 缺席；缺乏", 3, "cet4"),
    "absent": ("ˈæbsənt", "adj. 缺席的", 3, "cet4"),
    "absolute": ("ˈæbsəluːt", "adj. 绝对的", 4, "cet4"),
    "absorb": ("əbˈzɔːb", "v. 吸收", 4, "cet4"),
    "abstract": ("ˈæbstrækt", "adj. 抽象的 n. 摘要", 4, "cet4"),
    "absurd": ("əbˈsɜːd", "adj. 荒谬的", 4, "cet6"),
    "abundance": ("əˈbʌndəns", "n. 丰富", 4, "cet6"),
    "abuse": ("əˈbjuːz", "v./n. 滥用", 3, "cet4"),
    "academic": ("ˌækəˈdemɪk", "adj. 学术的", 3, "cet4"),
    "academy": ("əˈkædəmi", "n. 学院", 3, "cet4"),
    "accelerate": ("əkˈseləreɪt", "v. 加速", 4, "cet6"),
    "accent": ("ˈæksent", "n. 口音；重音", 3, "cet4"),
    "accept": ("əkˈsept", "v. 接受", 2, "cet4"),
    "acceptable": ("əkˈseptəbl", "adj. 可接受的", 3, "cet4"),
    "access": ("ˈækses", "n. 接近；通道", 3, "cet4"),
    "accessory": ("əkˈsesəri", "n. 附件；附属品", 4, "toefl"),
    "accident": ("ˈæksɪdənt", "n. 事故", 2, "cet4"),
    "accidental": ("ˌæksɪˈdentl", "adj. 意外的", 3, "cet4"),
    "accommodate": ("əˈkɒmədeɪt", "v. 容纳；适应", 4, "cet6"),
    "accompany": ("əˈkʌmpəni", "v. 陪伴；伴奏", 3, "cet4"),
    "accomplish": ("əˈkʌmplɪʃ", "v. 完成", 3, "cet4"),
    "accord": ("əˈkɔːd", "v. 给予 n. 一致", 4, "cet6"),
    "accordance": ("əˈkɔːdəns", "n. 一致", 4, "cet6"),
    "account": ("əˈkaʊnt", "n. 账户；描述", 2, "cet4"),
    "accumulate": ("əˈkjuːmjəleɪt", "v. 积累", 4, "cet6"),
    "accurate": ("ˈækjərət", "adj. 准确的", 3, "cet4"),
    "accuse": ("əˈkjuːz", "v. 指责", 3, "cet4"),
    "accustom": ("əˈkʌstəm", "v. 使习惯", 4, "cet6"),
    "achievement": ("əˈtʃiːvmənt", "n. 成就", 3, "cet4"),
    "acid": ("ˈæsɪd", "n. 酸 adj. 酸性的", 3, "cet4"),
    "acknowledge": ("əkˈnɒlɪdʒ", "v. 承认", 4, "cet6"),
    "acquaint": ("əˈkweɪnt", "v. 使熟悉", 4, "cet6"),
    "acquaintance": ("əˈkweɪntəns", "n. 熟人", 4, "cet6"),
    "acquire": ("əˈkwaɪər", "v. 获得", 4, "cet6"),
    "acquisition": ("ˌækwɪˈzɪʃn", "n. 获得；收购", 5, "toefl"),
    "acre": ("ˈeɪkər", "n. 英亩", 3, "cet4"),
    "across": ("əˈkrɒs", "prep./adv. 横过", 1, "cet4"),
    "act": ("ækt", "v. 行动 n. 行为", 1, "cet4"),
    "action": ("ˈækʃn", "n. 行动", 2, "cet4"),
    "active": ("ˈæktɪv", "adj. 活跃的", 2, "cet4"),
    "activity": ("ækˈtɪvəti", "n. 活动", 2, "cet4"),
    "actor": ("ˈæktər", "n. 演员", 2, "cet4"),
    "actress": ("ˈæktrəs", "n. 女演员", 2, "cet4"),
    "actual": ("ˈæktʃuəl", "adj. 实际的", 2, "cet4"),
    "actually": ("ˈæktʃuəli", "adv. 实际上", 2, "cet4"),
    "acute": ("əˈkjuːt", "adj. 急性的；敏锐的", 4, "cet6"),
    "adapt": ("əˈdæpt", "v. 适应；改编", 3, "cet4"),
    "adaptation": ("ˌædæpˈteɪʃn", "n. 适应；改编", 4, "cet6"),
    "add": ("æd", "v. 增加", 1, "cet4"),
    "addition": ("əˈdɪʃn", "n. 加；增加", 3, "cet4"),
    "additional": ("əˈdɪʃənl", "adj. 额外的", 3, "cet4"),
    "address": ("əˈdres", "n. 地址 v. 致辞", 2, "cet4"),
    "adequate": ("ˈædɪkwət", "adj. 足够的", 4, "cet6"),
    "adjust": ("əˈdʒʌst", "v. 调整", 3, "cet4"),
    "adjustment": ("əˈdʒʌstmənt", "n. 调整", 3, "cet4"),
    "administration": ("ədˌmɪnɪˈstreɪʃn", "n. 管理；行政", 4, "cet6"),
    "administrative": ("ədˈmɪnɪstreɪtɪv", "adj. 管理的", 4, "cet6"),
    "admire": ("ədˈmaɪər", "v. 钦佩", 3, "cet4"),
    "admission": ("ədˈmɪʃn", "n. 准许进入；承认", 4, "cet6"),
    "admit": ("ədˈmɪt", "v. 承认；准许进入", 3, "cet4"),
    "adopt": ("əˈdɒpt", "v. 收养；采用", 3, "cet4"),
    "adoption": ("əˈdɒpʃn", "n. 收养；采用", 4, "cet6"),
    "adult": ("ˈædʌlt", "n. 成年人", 2, "cet4"),
    "advance": ("ədˈvɑːns", "v. 前进 n. 进展", 3, "cet4"),
    "advanced": ("ədˈvɑːnst", "adj. 先进的；高级的", 3, "cet4"),
    "advantage": ("ədˈvɑːntɪdʒ", "n. 优势", 3, "cet4"),
    "advantageous": ("ˌædvənˈteɪdʒəs", "adj. 有利的", 4, "cet6"),
    "adventure": ("ədˈventʃər", "n. 冒险", 3, "cet4"),
    "adverb": ("ˈædvɜːb", "n. 副词", 3, "cet4"),
    "advertise": ("ˈædvətaɪz", "v. 做广告", 3, "cet4"),
    "advertisement": ("ədˈvɜːtɪsmənt", "n. 广告", 3, "cet4"),
    "advice": ("ədˈvaɪs", "n. 建议", 2, "cet4"),
    "advocate": ("ˈædvəkeɪt", "v. 提倡 n. 拥护者", 5, "gre"),
    "aerial": ("ˈeəriəl", "adj. 空中的 n. 天线", 4, "toefl"),
    "aeroplane": ("ˈeərəpleɪn", "n. 飞机", 2, "cet4"),
    "affair": ("əˈfeər", "n. 事情；事务", 3, "cet4"),
    "affect": ("əˈfekt", "v. 影响", 3, "cet4"),
    "affection": ("əˈfekʃn", "n. 喜爱；感情", 3, "cet4"),
    "afford": ("əˈfɔːd", "v. 买得起；承担", 3, "cet4"),
    "afraid": ("əˈfreɪd", "adj. 害怕的", 2, "cet4"),
    "Africa": ("ˈæfrɪkə", "n. 非洲", 1, "cet4"),
    "African": ("ˈæfrɪkən", "adj. 非洲的 n. 非洲人", 2, "cet4"),
    "after": ("ˈɑːftər", "prep./conj. 在...后", 1, "cet4"),
    "afternoon": ("ˌɑːftəˈnuːn", "n. 下午", 2, "cet4"),
    "afterward": ("ˈɑːftəwəd", "adv. 后来", 3, "cet4"),
    "again": ("əˈɡen", "adv. 再次", 1, "cet4"),
    "against": ("əˈɡenst", "prep. 反对；倚靠", 2, "cet4"),
    "age": ("eɪdʒ", "n. 年龄 v. 变老", 1, "cet4"),
    "agency": ("ˈeɪdʒənsi", "n. 代理处", 3, "cet4"),
    "agenda": ("əˈdʒendə", "n. 议程", 3, "cet4"),
    "agent": ("ˈeɪdʒənt", "n. 代理人；特工", 3, "cet4"),
    "aggressive": ("əˈɡresɪv", "adj. 侵略的；好斗的", 3, "cet4"),
    "ago": ("əˈɡəʊ", "adv. 以前", 1, "cet4"),
    "agony": ("ˈæɡəni", "n. 极大痛苦", 4, "cet6"),
    "agree": ("əˈɡriː", "v. 同意", 2, "cet4"),
    "agreeable": ("əˈɡriːəbl", "adj. 令人愉快的", 3, "cet4"),
    "agreement": ("əˈɡriːmənt", "n. 协议；同意", 3, "cet4"),
    "agriculture": ("ˈæɡrɪkʌltʃər", "n. 农业", 3, "cet4"),
    "ahead": ("əˈhed", "adv. 在前面", 1, "cet4"),
    "aid": ("eɪd", "n. 援助 v. 帮助", 2, "cet4"),
    "aim": ("eɪm", "n. 目标 v. 瞄准", 2, "cet4"),
    "air": ("eər", "n. 空气", 1, "cet4"),
    "aircraft": ("ˈeəkrɑːft", "n. 飞机；航空器", 2, "cet4"),
    "airline": ("ˈeəlaɪn", "n. 航空公司", 2, "cet4"),
    "airplane": ("ˈeərpleɪn", "n. 飞机", 2, "cet4"),
    "airport": ("ˈeərpɔːt", "n. 机场", 2, "cet4"),
    "alarm": ("əˈlɑːm", "n. 警报 v. 使惊恐", 2, "cet4"),
    "album": ("ˈælbəm", "n. 专辑；相册", 2, "cet4"),
    "alcohol": ("ˈælkəhɒl", "n. 酒精；酒", 3, "cet4"),
    "alert": ("əˈlɜːt", "adj. 警觉的 n. 警报", 3, "cet4"),
    "alien": ("ˈeɪliən", "n. 外星人 adj. 外国的", 3, "cet4"),
    "alike": ("əˈlaɪk", "adj. 相似的", 3, "cet4"),
    "alive": ("əˈlaɪv", "adj. 活着的", 2, "cet4"),
    "all": ("ɔːl", "adj. 所有的 adv. 全部", 1, "cet4"),
    "allergic": ("əˈlɜːdʒɪk", "adj. 过敏的", 4, "toefl"),
    "allergy": ("ˈælədʒi", "n. 过敏", 4, "toefl"),
    "allocate": ("ˈæləkeɪt", "v. 分配", 4, "cet6"),
    "allocation": ("ˌæləˈkeɪʃn", "n. 分配", 4, "cet6"),
    "allow": ("əˈlaʊ", "v. 允许", 2, "cet4"),
    "allowance": ("əˈlaʊəns", "n. 津贴；允许", 3, "cet4"),
    "ally": ("ˈælaɪ", "n. 同盟 v. 结盟", 3, "cet4"),
    "almost": ("ˈɔːlməʊst", "adv. 几乎", 2, "cet4"),
    "alone": ("əˈləʊn", "adj. 单独的 adv. 独自", 2, "cet4"),
    "along": ("əˈlɒŋ", "prep. 沿着 adv. 向前", 1, "cet4"),
    "alongside": ("əˌlɒŋˈsaɪd", "prep. 在...旁边", 3, "cet4"),
    "aloud": ("əˈlaʊd", "adv. 大声地", 2, "cet4"),
    "alphabet": ("ˈælfəbet", "n. 字母表", 2, "cet4"),
    "alter": ("ˈɔːltər", "v. 改变", 3, "cet4"),
    "alteration": ("ˌɔːltəˈreɪʃn", "n. 改变", 3, "cet4"),
    "alternative": ("ɔːlˈtɜːnətɪv", "n. 替代品 adj. 供选择的", 4, "cet4"),
    "although": ("ɔːlˈðəʊ", "conj. 虽然", 2, "cet4"),
    "altogether": ("ˌɔːltəˈɡeðər", "adv. 总共", 3, "cet4"),
    "always": ("ˈɔːlweɪz", "adv. 总是", 1, "cet4"),
    "amazing": ("əˈmeɪzɪŋ", "adj. 令人惊讶的", 3, "cet4"),
    "ambassador": ("æmˈbæsədər", "n. 大使", 4, "cet6"),
    "ambition": ("æmˈbɪʃn", "n. 野心；抱负", 3, "cet4"),
    "ambitious": ("æmˈbɪʃəs", "adj. 有雄心的", 4, "cet6"),
    "ambulance": ("ˈæmbjələns", "n. 救护车", 2, "cet4"),
    "among": ("əˈmʌŋ", "prep. 在...之中", 2, "cet4"),
    "amongst": ("əˈmʌŋst", "prep. 在...之中", 3, "cet4"),
    "amount": ("əˈmaʊnt", "n. 数量 v. 总计", 2, "cet4"),
    "amuse": ("əˈmjuːz", "v. 使娱乐", 3, "cet4"),
    "amusement": ("əˈmjuːzmənt", "n. 娱乐", 3, "cet4"),
    "analyse": ("ˈænəlaɪz", "v. 分析", 4, "cet6"),
    "analysis": ("əˈnæləsɪs", "n. 分析", 4, "cet6"),
    "analyze": ("ˈænəlaɪz", "v. 分析", 4, "cet6"),
    "ancestor": ("ˈænsestər", "n. 祖先", 3, "cet4"),
    "ancestral": ("ænˈsestrəl", "adj. 祖先的", 4, "gre"),
    "ancient": ("ˈeɪnʃənt", "adj. 古代的", 2, "cet4"),
    "and": ("ænd", "conj. 和", 1, "cet4"),
    "anecdote": ("ˈænɪkdəʊt", "n. 轶事", 5, "gre"),
    "angel": ("ˈeɪndʒl", "n. 天使", 2, "cet4"),
    "anger": ("ˈæŋɡər", "n. 愤怒 v. 使发怒", 2, "cet4"),
    "angle": ("ˈæŋɡl", "n. 角；角度", 2, "cet4"),
    "angry": ("ˈæŋɡri", "adj. 生气的", 2, "cet4"),
    "animal": ("ˈænɪml", "n. 动物", 1, "cet4"),
    "animate": ("ˈænɪmeɪt", "v. 使有生气", 4, "gre"),
    "anniversary": ("ˌænɪˈvɜːsəri", "n. 周年纪念", 3, "cet4"),
    "announce": ("əˈnaʊns", "v. 宣布", 3, "cet4"),
    "annoy": ("əˈnɔɪ", "v. 使烦恼", 3, "cet4"),
    "annual": ("ˈænjuəl", "adj. 每年的 n. 年刊", 3, "cet4"),
    "another": ("əˈnʌðər", "adj. 另一个 pron. 另一个", 1, "cet4"),
    "answer": ("ˈɑːnsər", "n. 答案 v. 回答", 1, "cet4"),
    "anticipate": ("ænˈtɪsɪpeɪt", "v. 预期；预料", 4, "cet6"),
    "anxiety": ("æŋˈzaɪəti", "n. 焦虑", 3, "cet4"),
    "anxious": ("ˈæŋkʃəs", "adj. 焦虑的", 3, "cet4"),
    "any": ("ˈeni", "adj. 任何的", 1, "cet4"),
    "anybody": ("ˈenibɒdi", "pron. 任何人", 2, "cet4"),
    "anyhow": ("ˈenihaʊ", "adv. 无论如何", 3, "cet4"),
    "anyone": ("ˈeniwʌn", "pron. 任何人", 1, "cet4"),
    "anything": ("ˈeniθɪŋ", "pron. 任何事物", 1, "cet4"),
    "anyway": ("ˈeniweɪ", "adv. 无论如何", 2, "cet4"),
    "anywhere": ("ˈeniweər", "adv. 任何地方", 2, "cet4"),
    "apart": ("əˈpɑːt", "adv. 分开；相隔", 2, "cet4"),
    "apartment": ("əˈpɑːtmənt", "n. 公寓", 2, "cet4"),
    "apologize": ("əˈpɒlədʒaɪz", "v. 道歉", 3, "cet4"),
    "apology": ("əˈpɒlədʒi", "n. 道歉", 3, "cet4"),
    "apparent": ("əˈpærənt", "adj. 明显的", 3, "cet4"),
    "appeal": ("əˈpiːl", "v. 呼吁 n. 吸引", 3, "cet4"),
    "appear": ("əˈpɪər", "v. 出现；似乎", 2, "cet4"),
    "appearance": ("əˈpɪərəns", "n. 外貌；出现", 3, "cet4"),
    "apple": ("ˈæpl", "n. 苹果", 1, "cet4"),
    "application": ("ˌæplɪˈkeɪʃn", "n. 申请；应用", 3, "cet4"),
    "apply": ("əˈplaɪ", "v. 申请；应用", 2, "cet4"),
    "appoint": ("əˈpɔɪnt", "v. 任命；约定", 3, "cet4"),
    "appointment": ("əˈpɔɪntmənt", "n. 任命；预约", 3, "cet4"),
    "appreciate": ("əˈpriːʃieɪt", "v. 感激；欣赏", 3, "cet4"),
    "approach": ("əˈprəʊtʃ", "v. 接近 n. 方法", 3, "cet4"),
    "appropriate": ("əˈprəʊpriət", "adj. 适当的", 4, "cet4"),
    "approval": ("əˈpruːvl", "n. 批准", 3, "cet4"),
    "approve": ("əˈpruːv", "v. 批准；赞成", 3, "cet4"),
    "approximate": ("əˈprɒksɪmət", "adj. 大约的 v. 接近", 4, "cet6"),
    "approximately": ("əˈprɒksɪmətli", "adv. 大约", 4, "cet6"),
    "arbitrary": ("ˈɑːbɪtrəri", "adj. 任意的", 4, "cet6"),
    "architect": ("ˈɑːkɪtekt", "n. 建筑师", 4, "cet6"),
    "architecture": ("ˈɑːkɪtektʃər", "n. 建筑学", 4, "cet6"),
    "area": ("ˈeəriə", "n. 地区；面积", 2, "cet4"),
    "argue": ("ˈɑːɡjuː", "v. 争论", 2, "cet4"),
    "argument": ("ˈɑːɡjumənt", "n. 论点；争吵", 3, "cet4"),
    "arise": ("əˈraɪz", "v. 出现；上升", 3, "cet4"),
    "arithmetic": ("əˈrɪθmətɪk", "n. 算术", 3, "cet4"),
    "arm": ("ɑːm", "n. 手臂 v. 武装", 1, "cet4"),
    "army": ("ˈɑːmi", "n. 军队", 1, "cet4"),
    "around": ("əˈraʊnd", "adv. 周围 prep. 大约", 1, "cet4"),
    "arrange": ("əˈreɪndʒ", "v. 安排", 3, "cet4"),
    "arrangement": ("əˈreɪndʒmənt", "n. 安排", 3, "cet4"),
    "arrest": ("əˈrest", "v./n. 逮捕", 3, "cet4"),
    "arrival": ("əˈraɪvl", "n. 到达", 3, "cet4"),
    "arrive": ("əˈraɪv", "v. 到达", 2, "cet4"),
    "arrow": ("ˈærəʊ", "n. 箭", 2, "cet4"),
    "art": ("ɑːt", "n. 艺术", 1, "cet4"),
    "article": ("ˈɑːrtɪkl", "n. 文章；物品", 2, "cet4"),
    "artificial": ("ˌɑːtɪˈfɪʃl", "adj. 人工的", 4, "cet6"),
    "artist": ("ˈɑːtɪst", "n. 艺术家", 2, "cet4"),
    "artistic": ("ɑːˈtɪstɪk", "adj. 艺术的", 3, "cet4"),
    "as": ("æz", "conj./adv. 作为；像", 1, "cet4"),
    "ash": ("æʃ", "n. 灰烬", 3, "cet4"),
    "ashamed": ("əˈʃeɪmd", "adj. 羞愧的", 3, "cet4"),
    "aside": ("əˈsaɪd", "adv. 在旁边", 2, "cet4"),
    "ask": ("æsk", "v. 询问；请求", 1, "cet4"),
    "asleep": ("əˈsliːp", "adj. 睡着的", 2, "cet4"),
    "aspect": ("ˈæspekt", "n. 方面", 3, "cet4"),
    "assess": ("əˈses", "v. 评估", 4, "cet6"),
    "assessment": ("əˈsesmənt", "n. 评估", 4, "cet6"),
    "asset": ("ˈæset", "n. 资产", 4, "toefl"),
    "assist": ("əˈsɪst", "v. 协助", 3, "cet4"),
    "assistance": ("əˈsɪstəns", "n. 协助", 3, "cet4"),
    "assistant": ("əˈsɪstənt", "n. 助手", 3, "cet4"),
    "associate": ("əˈsəʊʃieɪt", "v. 联想 n. 同事", 4, "cet6"),
    "association": ("əˌsəʊsiˈeɪʃn", "n. 协会；联想", 4, "cet6"),
    "assume": ("əˈsjuːm", "v. 假定；承担", 3, "cet4"),
    "assumption": ("əˈsʌmpʃn", "n. 假定", 4, "cet6"),
    "astonish": ("əˈstɒnɪʃ", "v. 使惊讶", 4, "cet6"),
    "at": ("æt", "prep. 在", 1, "cet4"),
    "athlete": ("ˈæθliːt", "n. 运动员", 3, "cet4"),
    "athletic": ("æθˈletɪk", "adj. 运动的", 3, "cet4"),
    "Atlantic": ("ətˈlæntɪk", "adj. 大西洋的", 2, "cet4"),
    "atmosphere": ("ˈætməsfɪər", "n. 大气；气氛", 4, "cet6"),
    "atom": ("ˈætəm", "n. 原子", 3, "cet4"),
    "attach": ("əˈtætʃ", "v. 系上；使依附", 3, "cet4"),
    "attack": ("əˈtæk", "v./n. 攻击", 2, "cet4"),
    "attempt": ("əˈtempt", "v./n. 尝试", 3, "cet4"),
    "attend": ("əˈtend", "v. 出席；照料", 3, "cet4"),
    "attention": ("əˈtenʃn", "n. 注意", 3, "cet4"),
    "attitude": ("ˈætɪtjuːd", "n. 态度", 3, "cet4"),
    "attorney": ("əˈtɜːni", "n. 律师", 3, "cet4"),
    "attract": ("əˈtrækt", "v. 吸引", 3, "cet4"),
    "attraction": ("əˈtrækʃn", "n. 吸引", 3, "cet4"),
    "attractive": ("əˈtræktɪv", "adj. 有吸引力的", 3, "cet4"),
    "attribute": ("əˈtrɪbjuːt", "v. 归因于", 4, "cet6"),
    "audience": ("ˈɔːdiəns", "n. 观众", 3, "cet4"),
    "author": ("ˈɔːθər", "n. 作者", 2, "cet4"),
    "authority": ("ɔːˈθɒrəti", "n. 权威；当局", 4, "cet6"),
    "automatic": ("ˌɔːtəˈmætɪk", "adj. 自动的", 4, "cet6"),
    "automation": ("ˌɔːtəˈmeɪʃn", "n. 自动化", 4, "cet6"),
    "automobile": ("ˈɔːtəməbiːl", "n. 汽车", 3, "cet4"),
    "autumn": ("ˈɔːtəm", "n. 秋天", 2, "cet4"),
    "available": ("əˈveɪləbl", "adj. 可用的", 3, "cet4"),
    "avenue": ("ˈævənjuː", "n. 大街；途径", 3, "cet4"),
    "average": ("ˈævərɪdʒ", "adj. 平均的 n. 平均", 2, "cet4"),
    "avoid": ("əˈvɔɪd", "v. 避免", 3, "cet4"),
    "await": ("əˈweɪt", "v. 等待", 3, "cet4"),
    "awake": ("əˈweɪk", "adj. 醒着的 v. 唤醒", 2, "cet4"),
    "award": ("əˈwɔːd", "n. 奖品 v. 授予", 3, "cet4"),
    "aware": ("əˈweər", "adj. 意识到的", 3, "cet4"),
    "away": ("əˈweɪ", "adv. 离开", 1, "cet4"),
    "awful": ("ˈɔːfl", "adj. 可怕的；非常的", 2, "cet4"),
    "awkward": ("ˈɔːkwəd", "adj. 尴尬的", 3, "cet4"),
    "axe": ("æks", "n. 斧头", 3, "cet4"),
    
    # B字母词汇
    "baby": ("ˈbeɪbi", "n. 婴儿", 1, "cet4"),
    "bachelor": ("ˈbætʃələr", "n. 单身汉；学士", 4, "cet6"),
    "back": ("bæk", "adj./adv. 后面 n. 背部", 1, "cet4"),
    "background": ("ˈbækɡraʊnd", "n. 背景", 2, "cet4"),
    "backward": ("ˈbækwəd", "adj. 向后的 adv. 向后", 2, "cet4"),
    "bacon": ("ˈbeɪkən", "n. 培根", 2, "cet4"),
    "bacterium": ("bækˈtɪəriəm", "n. 细菌", 4, "cet6"),
    "bad": ("bæd", "adj. 坏的", 1, "cet4"),
    "badly": ("ˈbædli", "adv. 坏；严重", 2, "cet4"),
    "badminton": ("ˈbædmɪntən", "n. 羽毛球", 2, "cet4"),
    "bag": ("bæɡ", "n. 包", 1, "cet4"),
    "baggage": ("ˈbæɡɪdʒ", "n. 行李", 2, "cet4"),
    "bake": ("beɪk", "v. 烘焙", 2, "cet4"),
    "bakery": ("ˈbeɪkəri", "n. 面包店", 2, "cet4"),
    "balance": ("ˈbæləns", "n. 平衡 v. 平衡", 2, "cet4"),
    "balcony": ("ˈbælkəni", "n. 阳台", 3, "cet4"),
    "ball": ("bɔːl", "n. 球；舞会", 1, "cet4"),
    "ballet": ("bæˈleɪ", "n. 芭蕾", 3, "cet4"),
    "balloon": ("bəˈluːn", "n. 气球", 2, "cet4"),
    "banana": ("bəˈnɑːnə", "n. 香蕉", 1, "cet4"),
    "band": ("bænd", "n. 乐队；带子", 2, "cet4"),
    "bandage": ("ˈbændɪdʒ", "n. 绷带", 3, "cet4"),
    "bank": ("bæŋk", "n. 银行；岸", 2, "cet4"),
    "banker": ("ˈbæŋkər", "n. 银行家", 3, "cet4"),
    "bar": ("bɑːr", "n. 条；酒吧", 2, "cet4"),
    "barber": ("ˈbɑːrbər", "n. 理发师", 2, "cet4"),
    "bare": ("beər", "adj. 赤裸的", 2, "cet4"),
    "bargain": ("ˈbɑːɡɪn", "n. 便宜货 v. 讨价还价", 3, "cet4"),
    "bark": ("bɑːrk", "v. 吠 n. 树皮", 2, "cet4"),
    "barn": ("bɑːrn", "n. 谷仓", 2, "cet4"),
    "barrel": ("ˈbærəl", "n. 桶", 2, "cet4"),
    "base": ("beɪs", "n. 基础 v. 基于", 2, "cet4"),
    "baseball": ("ˈbeɪsbɔːl", "n. 棒球", 2, "cet4"),
    "basic": ("ˈbeɪsɪk", "adj. 基本的", 2, "cet4"),
    "basically": ("ˈbeɪsɪkli", "adv. 基本上", 3, "cet4"),
    "basin": ("ˈbeɪsn", "n. 盆；流域", 3, "cet4"),
    "basis": ("ˈbeɪsɪs", "n. 基础", 3, "cet4"),
    "basket": ("ˈbæskɪt", "n. 篮子", 2, "cet4"),
    "basketball": ("ˈbæskɪtbɔːl", "n. 篮球", 2, "cet4"),
    "bat": ("bæt", "n. 球拍；蝙蝠", 2, "cet4"),
    "batch": ("bætʃ", "n. 一批", 3, "cet4"),
    "bath": ("bɑːθ", "n. 沐浴", 2, "cet4"),
    "bathe": ("beɪð", "v. 沐浴", 2, "cet4"),
    "bathroom": ("ˈbɑːθruːm", "n. 浴室", 2, "cet4"),
    "battery": ("ˈbætri", "n. 电池", 2, "cet4"),
    "battle": ("ˈbætl", "n./v. 战斗", 2, "cet4"),
    "bay": ("beɪ", "n. 湾", 2, "cet4"),
    "be": ("biː", "v. 是", 1, "cet4"),
    "beach": ("biːtʃ", "n. 海滩", 2, "cet4"),
    "beam": ("biːm", "n. 梁；光束", 3, "cet4"),
    "bean": ("biːn", "n. 豆", 2, "cet4"),
    "bear": ("beər", "n. 熊 v. 忍受", 2, "cet4"),
    "beard": ("bɪəd", "n. 胡须", 2, "cet4"),
    "beast": ("biːst", "n. 野兽", 2, "cet4"),
    "beat": ("biːt", "v. 打败 n. 节拍", 2, "cet4"),
    "beautiful": ("ˈbjuːtɪfl", "adj. 美丽的", 2, "cet4"),
    "beauty": ("ˈbjuːti", "n. 美丽", 2, "cet4"),
    "because": ("bɪˈkɒz", "conj. 因为", 1, "cet4"),
    "became": ("bɪˈkeɪm", "v. 变成", 1, "cet4"),
    "become": ("bɪˈkʌm", "v. 变成；成为", 1, "cet4"),
    "bed": ("bed", "n. 床", 1, "cet4"),
    "bedroom": ("ˈbedrum", "n. 卧室", 2, "cet4"),
    "bee": ("biː", "n. 蜜蜂", 1, "cet4"),
    "beef": ("biːf", "n. 牛肉", 2, "cet4"),
    "beer": ("bɪər", "n. 啤酒", 2, "cet4"),
    "before": ("bɪˈfɔːr", "prep./conj. 在...之前", 1, "cet4"),
    "beforehand": ("bɪˈfɔːrhænd", "adv. 事先", 3, "cet4"),
    "beg": ("beɡ", "v. 乞求；请求", 2, "cet4"),
    "begin": ("bɪˈɡɪn", "v. 开始", 1, "cet4"),
    "beginner": ("bɪˈɡɪnər", "n. 初学者", 2, "cet4"),
    "beginning": ("bɪˈɡɪnɪŋ", "n. 开始", 2, "cet4"),
    "behalf": ("bɪˈhɑːf", "n. 代表", 3, "cet4"),
    "behave": ("bɪˈheɪv", "v. 表现", 2, "cet4"),
    "behavior": ("bɪˈheɪvjər", "n. 行为", 3, "cet4"),
    "behind": ("bɪˈhaɪnd", "prep./adv. 在...后面", 1, "cet4"),
    "being": ("ˈbiːɪŋ", "n. 存在；生物", 2, "cet4"),
    "belief": ("bɪˈliːf", "n. 信念；信仰", 3, "cet4"),
    "believe": ("bɪˈliːv", "v. 相信", 2, "cet4"),
    "bell": ("bel", "n. 铃", 2, "cet4"),
    "belly": ("ˈbeli", "n. 腹部", 2, "cet4"),
    "belong": ("bɪˈlɒŋ", "v. 属于", 2, "cet4"),
    "below": ("bɪˈləʊ", "prep./adv. 在...下面", 1, "cet4"),
    "belt": ("belt", "n. 皮带；地带", 2, "cet4"),
    "bench": ("bentʃ", "n. 长椅", 2, "cet4"),
    "bend": ("bend", "v. 弯曲", 2, "cet4"),
    "beneath": ("bɪˈniːθ", "prep. 在...之下", 3, "cet4"),
    "beneficial": ("ˌbenɪˈfɪʃl", "adj. 有益的", 4, "cet6"),
    "benefit": ("ˈbenɪfɪt", "n./v. 利益", 3, "cet4"),
    "beside": ("bɪˈsaɪd", "prep. 在...旁边", 2, "cet4"),
    "besides": ("bɪˈsaɪdz", "prep./adv. 此外", 2, "cet4"),
    "best": ("best", "adj./adv. 最好的", 1, "cet4"),
    "bet": ("bet", "v. 打赌 n. 赌注", 2, "cet4"),
    "betray": ("bɪˈtreɪ", "v. 背叛", 4, "cet6"),
    "better": ("ˈbetər", "adj./adv. 更好的", 1, "cet4"),
    "between": ("bɪˈtwiːn", "prep. 在...之间", 1, "cet4"),
    "beyond": ("bɪˈjɒnd", "prep. 超越", 2, "cet4"),
    "bible": ("ˈbaɪbl", "n. 圣经", 2, "cet4"),
    "bicycle": ("ˈbaɪsɪkl", "n. 自行车", 2, "cet4"),
    "big": ("bɪɡ", "adj. 大的", 1, "cet4"),
    "bike": ("baɪk", "n. 自行车", 2, "cet4"),
    "bill": ("bɪl", "n. 账单；法案", 2, "cet4"),
    "billion": ("ˈbɪljən", "n. 十亿", 3, "cet4"),
    "bind": ("baɪnd", "v. 绑；约束", 3, "cet4"),
    "biology": ("baɪˈɒlədʒi", "n. 生物学", 4, "cet6"),
    "bird": ("bɜːrd", "n. 鸟", 1, "cet4"),
    "birth": ("bɜːθ", "n. 出生", 2, "cet4"),
    "birthday": ("ˈbɜːθdeɪ", "n. 生日", 2, "cet4"),
    "biscuit": ("ˈbɪskɪt", "n. 饼干", 2, "cet4"),
    "bit": ("bɪt", "n. 少量；一点", 1, "cet4"),
    "bite": ("baɪt", "v. 咬", 2, "cet4"),
    "bitter": ("ˈbɪtər", "adj. 苦的", 3, "cet4"),
    "black": ("blæk", "adj. 黑色的", 1, "cet4"),
    "blackboard": ("ˈblækbɔːrd", "n. 黑板", 2, "cet4"),
    "blame": ("bleɪm", "v./n. 责备", 2, "cet4"),
    "blank": ("blæŋk", "adj. 空白的 n. 空白", 2, "cet4"),
    "blanket": ("ˈblæŋkɪt", "n. 毯子", 2, "cet4"),
    "blast": ("blæst", "n. 爆炸 v. 爆破", 3, "cet4"),
    "blaze": ("bleɪz", "n. 火焰 v. 燃烧", 3, "cet4"),
    "bleed": ("bliːd", "v. 出血", 3, "cet4"),
    "blend": ("blend", "v. 混合", 3, "cet4"),
    "bless": ("bles", "v. 祝福", 3, "cet4"),
    "blind": ("blaɪnd", "adj. 瞎的", 3, "cet4"),
    "block": ("blɒk", "n. 街区 v. 阻挡", 2, "cet4"),
    "blood": ("blʌd", "n. 血", 2, "cet4"),
    "bloom": ("bluːm", "v. 开花 n. 花", 3, "cet4"),
    "blouse": ("blaʊz", "n. 女衬衫", 2, "cet4"),
    "blow": ("bləʊ", "v. 吹", 2, "cet4"),
    "blue": ("bluː", "adj. 蓝色的", 1, "cet4"),
    "blueprint": ("ˈbluːprɪnt", "n. 蓝图", 4, "cet6"),
    "board": ("bɔːrd", "n. 板；董事会", 2, "cet4"),
    "boast": ("bəʊst", "v. 自夸", 3, "cet4"),
    "boat": ("bəʊt", "n. 船", 2, "cet4"),
    "body": ("ˈbɒdi", "n. 身体", 1, "cet4"),
    "boil": ("bɔɪl", "v. 沸腾", 2, "cet4"),
    "bomb": ("bɒm", "n. 炸弹", 2, "cet4"),
    "bond": ("bɒnd", "n. 结合；债券", 3, "cet4"),
    "bone": ("bəʊn", "n. 骨头", 2, "cet4"),
    "book": ("bʊk", "n. 书 v. 预订", 1, "cet4"),
    "bookshelf": ("ˈbʊkʃelf", "n. 书架", 2, "cet4"),
    "bookstore": ("ˈbʊkstɔːr", "n. 书店", 2, "cet4"),
    "boom": ("buːm", "n. 繁荣 v. 激增", 3, "cet4"),
    "boost": ("buːst", "v. 促进；增加", 3, "cet4"),
    "boot": ("buːt", "n. 靴子", 2, "cet4"),
    "border": ("ˈbɔːrdər", "n. 边界", 2, "cet4"),
    "bore": ("bɔːr", "v. 使厌烦", 2, "cet4"),
    "bored": ("bɔːrd", "adj. 厌倦的", 2, "cet4"),
    "boring": ("ˈbɔːrɪŋ", "adj. 无聊的", 2, "cet4"),
    "born": ("bɔːrn", "adj. 天生的", 2, "cet4"),
    "borrow": ("ˈbɒrəʊ", "v. 借", 2, "cet4"),
    "boss": ("bɒs", "n. 老板", 2, "cet4"),
    "both": ("bəʊθ", "pron./adj. 两者", 1, "cet4"),
    "bother": ("ˈbɒðər", "v. 打扰", 2, "cet4"),
    "bottle": ("ˈbɒtl", "n. 瓶子", 2, "cet4"),
    "bottom": ("ˈbɒtəm", "n./adj. 底部", 2, "cet4"),
    "bounce": ("baʊns", "v. 弹起", 3, "cet4"),
    "bound": ("baʊnd", "adj. 必定的；受约束的", 3, "cet4"),
    "boundary": ("ˈbaʊndri", "n. 边界", 3, "cet4"),
    "bow": ("baʊ", "v. 鞠躬 n. 弓", 2, "cet4"),
    "bowl": ("bəʊl", "n. 碗", 2, "cet4"),
    "box": ("bɒks", "n. 盒子 v. 拳击", 1, "cet4"),
    "boxer": ("ˈbɒksər", "n. 拳击手", 2, "cet4"),
    "boy": ("bɔɪ", "n. 男孩", 1, "cet4"),
    "boyfriend": ("ˈbɔɪfrend", "n. 男朋友", 2, "cet4"),
    "brain": ("breɪn", "n. 大脑", 2, "cet4"),
    "brake": ("breɪk", "n. 刹车 v. 刹车", 3, "cet4"),
    "branch": ("bræntʃ", "n. 树枝；分部", 2, "cet4"),
    "brand": ("brænd", "n. 品牌", 2, "cet4"),
    "brave": ("breɪv", "adj. 勇敢的", 2, "cet4"),
    "bread": ("bred", "n. 面包", 2, "cet4"),
    "break": ("breɪk", "v. 打破；休息", 1, "cet4"),
    "breakfast": ("ˈbrekfəst", "n. 早餐", 2, "cet4"),
    "breast": ("brest", "n. 胸部", 3, "cet4"),
    "breath": ("breθ", "n. 呼吸", 2, "cet4"),
    "breathe": ("briːð", "v. 呼吸", 2, "cet4"),
    "breed": ("briːd", "v. 繁殖；饲养", 3, "cet4"),
    "brick": ("brɪk", "n. 砖", 2, "cet4"),
    "bride": ("braɪd", "n. 新娘", 3, "cet4"),
    "bridge": ("brɪdʒ", "n. 桥", 2, "cet4"),
    "brief": ("briːf", "adj. 简短的", 3, "cet4"),
    "bright": ("braɪt", "adj. 明亮的；聪明的", 2, "cet4"),
    "brilliant": ("ˈbrɪliənt", "adj. 杰出的", 3, "cet4"),
    "bring": ("brɪŋ", "v. 带来", 1, "cet4"),
    "broad": ("brɔːd", "adj. 宽阔的", 2, "cet4"),
    "broadcast": ("ˈbrɔːdkæst", "n./v. 广播", 3, "cet4"),
    "brochure": ("ˈbrəʊʃər", "n. 小册子", 4, "toefl"),
    "broken": ("ˈbrəʊkən", "adj. 破碎的", 2, "cet4"),
    "broom": ("bruːm", "n. 扫帚", 2, "cet4"),
    "brother": ("ˈbrʌðər", "n. 兄弟", 1, "cet4"),
    "brown": ("braʊn", "n./adj. 棕色", 2, "cet4"),
    "brush": ("brʌʃ", "n./v. 刷子；刷", 2, "cet4"),
    "budget": ("ˈbʌdʒɪt", "n. 预算", 3, "cet4"),
    "build": ("bɪld", "v. 建造", 2, "cet4"),
    "building": ("ˈbɪldɪŋ", "n. 建筑物", 2, "cet4"),
    "bulb": ("bʌlb", "n. 灯泡", 2, "cet4"),
    "bulk": ("bʌlk", "n. 大部分；体积", 3, "cet4"),
    "bull": ("bʊl", "n. 公牛", 2, "cet4"),
    "bullet": ("ˈbʊlɪt", "n. 子弹", 3, "cet4"),
    "bump": ("bʌmp", "v. 撞击 n. 肿块", 2, "cet4"),
    "bunch": ("bʌntʃ", "n. 束；群", 2, "cet4"),
    "bundle": ("ˈbʌndl", "n. 束；包", 3, "cet4"),
    "burden": ("ˈbɜːrdn", "n. 负担", 3, "cet4"),
    "bureau": ("ˈbjʊərəʊ", "n. 局", 3, "cet4"),
    "burn": ("bɜːrn", "v. 燃烧", 2, "cet4"),
    "burst": ("bɜːrst", "v. 爆裂 n. 爆发", 3, "cet4"),
    "bury": ("ˈberi", "v. 埋葬", 3, "cet4"),
    "bus": ("bʌs", "n. 公共汽车", 2, "cet4"),
    "bush": ("bʊʃ", "n. 灌木", 2, "cet4"),
    "business": ("ˈbɪznɪs", "n. 生意；事务", 3, "cet4"),
    "businessman": ("ˈbɪznɪsmæn", "n. 商人", 3, "cet4"),
    "busy": ("ˈbɪzi", "adj. 忙碌的", 2, "cet4"),
    "but": ("bʌt", "conj. 但是", 1, "cet4"),
    "butcher": ("ˈbʊtʃər", "n. 屠夫", 2, "cet4"),
    "butter": ("ˈbʌtər", "n. 黄油", 2, "cet4"),
    "button": ("ˈbʌtn", "n. 按钮", 2, "cet4"),
    "buy": ("baɪ", "v. 买", 1, "cet4"),
    "buyer": ("ˈbaɪər", "n. 买者", 2, "cet4"),
    "by": ("baɪ", "prep. 被；通过", 1, "cet4"),
    "bye": ("baɪ", "int. 再见", 1, "cet4"),
}

print(f"Total vocabulary in database: {len(COMPREHENSIVE_VOCABULARY)}")
